### ISSUE TITLE
Synchronous is evil?

### ISSUE THREAD

**Issue by MajorBreakfast** [joliss/node-walk-sync#1]
What about going asynchronous using promises and stating multiple files at once?

**Comment by evanplaice** [comment]
Are you using HDD or SSD for the benchmarks? The way that SSDs access data is fundamentally different from how HDDs access data.

> *4. NAND-flash pages and blocks*
> Cells are grouped into a grid, called a block, and blocks are grouped into planes. The smallest unit through which a block can be read or written is a page. Pages cannot be erased individually, only whole blocks can be erased. The size of a NAND-flash page size can vary, and most drive have pages of size 2 KB, 4 KB, 8 KB or 16 KB. Most SSDs have blocks of 128 or 256 pages, which means that the size of a block can vary between 256 KB and 4 MB. For example, the Samsung SSD 840 EVO has blocks of size 2048 KB, and each block contains 256 pages of 8 KB each.

> *21. A large single-threaded read is better than many small concurrent reads*
> Concurrent random reads cannot fully make use of the readahead mechanism. In addition, multiple Logical Block Addresses may end up on the same chip, not taking advantage or of the internal parallelism. A large read operation will access sequential addresses and will therefore be able to use the readahead buffer if present, and use the internal parallelism. Consequently if the use case allows it, it is better to issue a large read request.

**Source:**
**http://codecapsule.com/2014/02/12/coding-for-ssds-part-6-a-summary-what-every-programmer-should-know-about-solid-state-drives/**

Following that reasoning, it would make sense that read performance would be better on a SSD when handled in a synchronous manner.

**Comment by stefanpenner** [comment]
@evanplaice I did some splunking when @MajorBreakfast pointed out the unix/windows difference. If memory serves it seemed to boil down to how libuv handles async and sync on each platform. On win the async path is merely more optimal. When comparing, I recall the unix async path looked like it could be further optimized. This was quite some time ago and the state of libuv may have changed

**Comment by stefanpenner** [comment]
@joliss I think we can close this.
