### ISSUE TITLE
published package contains many files

### ISSUE THREAD

**Issue by stefanpenner** [joliss/node-walk-sync#14]
we should likely just whitelist `index.js`

**Comment by joliss** [comment]
Yup, fixed and released in 0.2.5.

**Comment by joliss** [comment]
Negation in `.npmignore` (e.g. `!/index.js`) doesn't work for me, even though the docs suggest it should work. Not sure why. So I just blacklisted everything else.

**Comment by stefanpenner** [comment]
> Not sure why.

npm is full of mysteries.
