### ISSUE TITLE
ensureing path sufix deserve minior version dump

### ISSUE THREAD

**Issue by chrmod** [joliss/node-walk-sync#21]
There are broccoli plugins relying on previous behavior (0.2.5), like broccoli-sourcemap-concat https://github.com/ef4/broccoli-sourcemap-concat/blob/master/concat.js#L153

With patched version being released those plugins are broken on Windows. 

Commit that breaks previous behavior: https://github.com/joliss/node-walk-sync/commit/a1c0486f58be8f14ff3e29ac2cf86875bde9222d#diff-168726dbe96b3ce427e7fedce31bb0bcR28

**Comment by stefanpenner** [comment]
@chrmod can you provide an example that fails, my windows machine seems to be running it without trouble.

**Comment by stefanpenner** [comment]
this seems to have gone stale, will gladly reopen if my above comment can be addressed.

**Comment by lllama** [comment]
I believe this is related to an issue I'm having with https://github.com/ming-codes/ember-cli-d3. If you clone that repo on Windows, then do `npm install`, `bower install` and finally `ember test` you should get an exception being thrown due to a non-posix path related error.
