### ISSUE TITLE
add { ignore: [globs] }

### ISSUE THREAD

**Issue by stefanpenner** [joliss/node-walk-sync#23]
Often the current whitelist globs do the trick, but implementing the blacklist performantly is non-obvious and sometimes not possible.

I'm leaving this as a place-holder, I intend to implement this sometime. But if someone beats me to it, I will not be offended.

---

My thoughts are as follows:

```
walkSync(root, { ignore: [array, of, globs/strings] });
```

Similar to, https://github.com/joliss/node-walk-sync/blob/master/index.js#L53-L55 we would just prune a dir early. And instead of `mayContain` I believe we must use an explicit `match`, which `MatcherCollection` [already supports](https://github.com/stefanpenner/matcher-collection/blob/master/index.js#L13-L21)

Then finally before appending to the output paths, a full check should occur.

All of this should be pay as you go, if people don't use it we should avoid those branches.

**Comment by alexlafroscia** [comment]
Is there a way to get this kind of behavior right now? I'm working on [this PR](https://github.com/ember-cli/ember-cli-eslint/pull/91) right now and after hearing you mention this project last night at the Ember meetup, figured it was worth checking to see if this is faster than the [glob package](https://github.com/isaacs/node-glob) that I'm using right now.  I want to be able to explicitly avoid walking through the whole `node_modules` and `bower_components` directories since they're often pretty huge and I don't care about the files in it.

**Comment by stefanpenner** [comment]
@alexlafroscia in many cases walkSync will just do the right thing (no need to ignore) as it decomposes the globs to prune directories early.

For example:

```
walkSync('.', ['bower_components/jquery/**/*.js', 'app/**/*.js']
```

Will be smart enough to only traverse the following deeply `app/**/*` and `bower_components/jquery/**/*` and `'.` shallow, even though the root is at `.`

**Comment by stefanpenner** [comment]
but yes, in your case `glob('**/.jshintrc'` would be the canonical example of when a blacklist would be good. Currently this isn't possible (as the issue describes) but it would be great to have this functionality added.

**Comment by alexlafroscia** [comment]
Gotcha, thanks for the pointers. I'll look into some of those links you provided above and see if I can get a PR together to implement this.

**Comment by alexlafroscia** [comment]
Anything else I should know before trying it out?

**Comment by stefanpenner** [comment]
@alexlafroscia not that I can think of, feel free to submit a PR early (here or maybe matcher-collection) so I can provide feedback and help guide.

**Comment by alexlafroscia** [comment]
Sounds good!

**Comment by stefanpenner** [comment]
@alexlafroscia awesome, I am excited to get a hand \w this. It seems like your use-case is perfect.
