### ISSUE TITLE
walk-sync should resolve check symlink isn't to something it has already visited

### ISSUE THREAD

**Issue by krisselden** [joliss/node-walk-sync#30]
this leads to infinite recursion then eventually to ENAMETOOLONG

**Comment by joliss** [comment]
I recently noticed that we used to have code to detect symlink loops in an (unrelated, walk-like) function in broccoli-kitchen-sink-helpers, but @rwjblue [took it out](https://github.com/broccolijs/broccoli-kitchen-sink-helpers/commit/eec3ece3e019a7824ac272e4aa6bec4d91578ccf#diff-168726dbe96b3ce427e7fedce31bb0bcL52) a while back. When I looked at it I concluded that the ENAMETOOLONG error is clear enough that it was perhaps OK not to bother detecting symlink loops.

Have you found this to be an actual usability issue?

Maybe @rwjblue has some thoughts as well.

**Comment by krisselden** [comment]
@joliss ENAMETOOLONG helps detect the error, what I was hoping is that it would not add another entry instead of failing, it was causing trouble with the way lerna symlinks packages if they had a circular ref, and various broccoli plugins that use walk sync.  It seemed like it would be simple just to guard reentry.

**Comment by stefanpenner** [comment]
@krisselden ya, I think breaking the cycle is the "least surprising behavior"

**Comment by stefanpenner** [comment]
fised
