### ISSUE TITLE
Add option for including path in all results

### ISSUE THREAD

**Issue by MJCD** [joliss/node-walk-sync#32]

**Comment by stefanpenner** [comment]
@MJCD I don't understand, can you maybe add a more detailed description/examples?

**Comment by zeke** [comment]
Hi there. Long time and frequent user of `walk-sync` here. I think what's being suggested here is that it would be nice to optionally include the _full_ path to each file. When I using walk-sync, I almost always end up constructing the full path, like this:

```js
const path = require('path')
const basePath = path.join(__dirname, 'some/dir')
const walk = require('walk-sync')

// extra mapping needed to get full paths
const filenames = walk(basePath).map(relativePath => {
  return path.join(basePath, relativePath)
})

// and when using walk.entries:
walk.entries(basePath).forEach(entry => {
  entry.fullPath = path.join(basePath, entry.relativePath)
  // etc...
})
```

Adding support for an option like `fullPath` would be convenient.

**Comment by zeke** [comment]
I just looked in the source and it appears there's an option called `includeBasePath` that does exactly this (but only for the default function not for `.entries), which is great! It's just not documented in the README. If this library is still maintained, I'd be happy to open a PR adding this option to the documentation.

**Comment by stefanpenner** [comment]
> > If this library is still maintained
> Yup it is still maintained, just low activity since its it a pretty stable state.

I've bumped to 1.0.0, since its pretty stable the version number can now safely convey some confidence :)

**Comment by zeke** [comment]
> 1.0.0

🎉

**Comment by MJCD** [comment]
Thanks very much for your assistance on this. Kudos to @stefanpenner
