### ISSUE TITLE
Published d.ts refers to devDependency

### ISSUE THREAD

**Issue by ef4** [joliss/node-walk-sync#42]
walk-sync 1.1.2 broke my typescript build:

```
node_modules/walk-sync/index.d.ts:1:28 - error TS7016: Could not find a declaration file for module 'minimatch'. '/XXX/node_modules/minimatch/minimatch.js' implicitly has an 'any' type.
  Try `npm install @types/minimatch` if it exists or add a new declaration (.d.ts) file containing `declare module 'minimatch';`

1 import { IMinimatch } from 'minimatch';
                             ~~~~~~~~~~~
```

My project uses `compilerOptions: { strict: true }`.

On the one hand, it seems bad to have a file published to NPM that imports a `devDependency`. But I can understand why you might not want to put `@types/minimatch` in `dependencies`, since presumably non-TS users won't care about it.

I can workaround by adding `@types/minimatch` directly to my project.

**Comment by stefanpenner** [comment]
Sorry typescript noob here.

**Comment by ef4** [comment]
Yeah I really don’t know what’s ideal here either.

**Comment by stefanpenner** [comment]
I think publishing the types is fine :)
