### ISSUE TITLE
"Error: Cannot find module 'walk-sync'" after switching to 2.0.0

### ISSUE THREAD

**Issue by danielholmes** [joliss/node-walk-sync#46]
The `2.0.0` release looks like it doesn't include `index.js` when I install in my project. The release archive itself also doesn't include index.js (just index.ts): https://github.com/joliss/node-walk-sync/releases/tag/v2.0.0

**Comment by rwjblue** [comment]
Eeeck, thanks for reporting! 

@stefanpenner - Have a minute to double check and fix (I don't think I have commit / npm access here)?

**Comment by rwjblue** [comment]
Seems like we need to add `yarn build` as a `prepare` script (or something like that), to help ensure when `npm publish`ing we actually have done the build first...

**Comment by stefanpenner** [comment]
Oops this is my bad.

- [x] add prepare: https://github.com/joliss/node-walk-sync/commit/a0ec32d0e01721e518c1018c406b2a71287129c7
- [x] release 2.0.1: https://github.com/joliss/node-walk-sync/commit/b75fa80dbc9dff09b65d115fb5e95ae2725d8165

**Comment by stefanpenner** [comment]
Also, confirmed that both the packed package, and the published one functioned correctly.
