### ISSUE TITLE
Filesystem object supplied as option

### ISSUE THREAD

**Issue by elmpp** [joliss/node-walk-sync#52]
Hi there,

Would you accept a PR that would allow the fs-like object to be supplied as an option?

It would be great to allow different filesystem implementations to be walked by this package also. My use case would be an [memfs volume](https://github.com/streamich/memfs/blob/02082dbfe5fecab10d81afce55e4f3180b38eba8/src/volume.ts#L516) but could just as also easily be a [graceful-fs](https://github.com/isaacs/node-graceful-fs#readme) fs-like

I imagine it would not be a breaking change and the api would be:

```ts
const memfsVol = Volume.fromJSON({'/aFile': 'contents'})
const paths = walkSync('project', { globs: ['subdir/**/*.txt'], fs: memfsVol });
```

**Comment by rwjblue** [comment]
Seems generally fine to me, not sure how easy/hard the changes would be though.

**Comment by elmpp** [comment]
@rwjblue I've opened a PR, be grateful if you'd take a look thanks.

**Comment by stefanpenner** [comment]
The PR has been merged, and released. Thank you!
