### ISSUE TITLE
Default false for directories option

### ISSUE THREAD

**Issue by rajasegar** [joliss/node-walk-sync#55]
Most of the time, we use this library to iterate the files inside a path, but it also returns the directories always since true is the default value. It would be great to have `directories: false` as default value so that we don't have to pass `{ directories: false }` everytime. It would be a better sensible default IMHO

**Comment by rwjblue** [comment]
I haven't thought too much about it, lots of the broccoli related tooling that leverages this lib used the directory entry to know to create subdirs and whatnot (avoiding the penalty of calling `mkdir -p` too often).

I do tend to share your perspective here though, that the cases where you _want_ the directory entries are much fewer than the ones where you don't.

**Comment by stefanpenner** [comment]
Although this may be true, even with a major version bump this change seems like an upgrade hazard, so I'm not sure its worth making the change.

**Comment by rajasegar** [comment]
Thanks, @stefanpenner @rwjblue that makes perfect sense.
